"use client";

import { useEffect, useRef, useState } from "react";
import { load } from "@apple/mapkit-loader";
import type { Map as MapKitMap } from "@apple/mapkit-loader";
import {
  CLUSTER_ID,
  clusterLabel,
  MAP_INSET,
  mapkitLibraries,
  mapkitToken,
  mapkitTokenExpired,
  mapkitTokenExpiry,
  mapPins,
  mapRegion,
} from "@/lib/maps";

/* The live Apple map. Mounted only once someone asks for it (PlacesExplorer),
   so this file — and the ~300KB of MapKit JS behind it — is a separate chunk
   that a normal visit never downloads.

   Every colour comes back out of the stylesheet at runtime rather than being
   written here: MapKit wants strings, and reading --color-accent keeps the
   one-token-source rule intact instead of forking the coral into JS. */

type Status = "loading" | "ready" | "error";

const cssToken = (name: string) =>
  getComputedStyle(document.documentElement).getPropertyValue(name).trim();

export default function PlacesMap() {
  const container = useRef<HTMLDivElement>(null);
  const [status, setStatus] = useState<Status>("loading");

  useEffect(() => {
    let map: MapKitMap | undefined;
    let cancelled = false;
    let detachError: (() => void) | undefined;

    /* Said before the load rather than after the failure, because MapKit's own
       report of it says only that a loader failed. Not gated on NODE_ENV: it
       fires only when the token is already dead, which is the state where a
       line in the console is the most useful thing on the page. */
    if (mapkitTokenExpired()) {
      console.warn(
        `[places] The MapKit token expired on ${new Date(mapkitTokenExpiry!)
          .toISOString()
          .slice(0, 10)}. Apple will answer 401 and the map will show its ` +
          "fallback. Issue a new one under Certificates, Identifiers & " +
          "Profiles → Maps Tokens, set NEXT_PUBLIC_MAPKIT_TOKEN in .env.local, " +
          "and restart the dev server — Next inlines it at build time."
      );
    }

    (async () => {
      try {
        const mapkit = await load({
          token: mapkitToken,
          libraries: mapkitLibraries,
        });
        if (cancelled || !container.current) return;

        /* A rejected token does not reject load() — the script fetches fine and
           Apple turns it down afterwards, so the only signal is this event.
           Without it a bad or over-quota token leaves a silent empty box. */
        const onError = () => {
          if (!cancelled) setStatus("error");
        };
        mapkit.addEventListener("error", onError);
        detachError = () => mapkit.removeEventListener("error", onError);

        const accent = cssToken("--color-accent");
        const onAccent = cssToken("--color-on-dark");
        const still = window.matchMedia("(prefers-reduced-motion: reduce)").matches;

        map = new mapkit.Map(container.current, {
          /* MutedStandard is the one map type that lets the page's own colour
             lead — closest MapKit gets to the flat monochrome §7 asks for. */
          mapType: mapkit.MapType.MutedStandard,
          /* Light, not Adaptive: the site has no dark mode, and a dark map
             inside a paper-white card reads as a bug. */
          colorScheme: mapkit.ColorScheme.Light,
          showsPointsOfInterest: false,
          showsMapTypeControl: false,
          showsUserLocationControl: false,
          showsScale: mapkit.FeatureVisibility.Hidden,
          showsCompass: mapkit.FeatureVisibility.Hidden,
          isRotationEnabled: false,
          /* Merged balloons are generated by MapKit, so they inherit none of
             the styling below — without this they arrive in MapKit's default
             red and captioned "Hamburg +4 more", which speaks for four cities
             it does not name. Restyled to the accent and labelled the way the
             SVG labels its merged dots. */
          annotationForCluster: (cluster) => {
            const members = cluster.memberAnnotations;
            const countries = members.map(
              (member) => (member.data as { country?: string })?.country ?? ""
            );
            cluster.color = accent;
            cluster.glyphColor = onAccent;
            cluster.glyphText = String(members.length);
            cluster.title = clusterLabel(countries);
            cluster.subtitle = "";
            return cluster;
          },
          region: new mapkit.CoordinateRegion(
            new mapkit.Coordinate(mapRegion.centerLat, mapRegion.centerLng),
            new mapkit.CoordinateSpan(
              mapRegion.latitudeDelta,
              mapRegion.longitudeDelta
            )
          ),
        });

        const pins = mapPins.map(
          (pin) =>
            new mapkit.MarkerAnnotation(
              new mapkit.Coordinate(pin.lat, pin.lng),
              {
                title: pin.title,
                subtitle: pin.subtitle,
                color: accent,
                glyphColor: onAccent,
                clusteringIdentifier: CLUSTER_ID,
                /* Read back out in annotationForCluster to caption a merge. */
                data: { country: pin.country },
                accessibilityLabel: `${pin.title} — ${pin.subtitle}`,
              }
            )
        );

        map.addAnnotations(pins);
        /* The constructor region frames the coordinates; this reframes around
           the balloons themselves, which stand above their pin. */
        map.showItems(pins, {
          animate: !still,
          padding: new mapkit.Padding({
            top: MAP_INSET,
            right: MAP_INSET,
            bottom: MAP_INSET,
            left: MAP_INSET,
          }),
        });

        setStatus("ready");
      } catch {
        if (!cancelled) setStatus("error");
      }
    })();

    /* mapkit is a singleton that outlives this component, so the listener has
       to come back off or every open/close cycle leaves one behind. */
    return () => {
      cancelled = true;
      detachError?.();
      map?.destroy();
    };
  }, []);

  return (
    <div className="places-map places-live" data-status={status}>
      <div className="places-canvas" ref={container} />
      {status !== "ready" && (
        <p className="places-status" role="status">
          {status === "loading" ? "Loading the map…" : "The map didn’t load."}
        </p>
      )}
    </div>
  );
}
